spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LIANJOY;encrypt=true;trustServerCertificate=true
spring.datasource.username=Proyecto-sem
spring.datasource.password=0717

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Para ver qué consultas SQL hace Spring en la consola (útil para aprender)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# Tamaño máximo del archivo (ejemplo 5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB